server:
  port: 8888
  ssl:
    client-auth: none
    key-store-type: PKCS12
    key-alias: server
    key-store: classpath:server.p12
    key-store-password: fgq666
#    trust-store-type: PKCS12
#    trust-store: classpath:server.p12
#    trust-store-password: fgq666
