server:
  port: 9002
spring:
  application:
    name: oauth2-source
security:
  oauth2:
    client:
      client-id: admin
      client-secret: admin123456
      access-token-uri: http://127.0.0.1:9001/oauth/token
      user-authorization-uri: http://127.0.0.1:9001/oauth/authorize
    resource:
      token-info-uri: http://127.0.0.1:9001/oauth/check_token


