server:
  port: 8888
spring:
  application:
    name: springboot-elasticsearch
  mvc:
    view:
      suffix: .html
  elasticsearch:
    rest:
      uris: http://172.28.1.236:9200
      username: elastic
      password: 123456
      connection-timeout: 5
      read-timeout: 30
  data:
    elasticsearch:
      repositories:
        enabled: true
  datasource:
    url: jdbc:mysql://172.28.1.236:3306/es?useSSL=false&serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: fgq
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
logging:
  level:
    com.elasticsearch.demo: warn
  pattern:
    dateformat: HH:mm:ss
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mybatis/*.xml
