server:
  port: 8081
spring:
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    packages:
      trust-all: true
  jms:
    pub-sub-domain: false   # 点对点 false(默认)、发布订阅 true
    template:
      delivery-mode: persistent
