server:
  port: 9001
spring:
  application:
    name: oauth2-server-jdbc
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/oauth2?useSSL=false&serverTimezone=UTC
    username: root
    password: 19931126
    driver-class-name: com.mysql.cj.jdbc.Driver